- hosts: gitlab
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - ansible_vars.yml
  handlers:
    - name: Start postfix
      systemd:
        name: postfix
        state: started
        enabled: yes
    - name: Start sshd
      systemd:
        name: ssh
        state: started
        enabled: yes
    - name: Reconfigure GitLab
      command: gitlab-ctl reconfigure
    - name: Reconfigure and restart GitLab
      shell: gitlab-ctl reconfigure && gitlab-ctl restart

  tasks:
    - name: Install GitLab dependencies
      apt:
        name:
          - curl
          - openssh-server
          - ca-certificates
          - postfix
        state: present
        update_cache: yes
      notify:
        - Start sshd
        - Start postfix
    - name: Run script to check system and add repository for GitLab CE
      shell: "curl -L -s {{ gitlab_script_url }} | bash"
    - name: Install Gitlab CE
      apt:
        name: "{{ gitlab_package }}"
        state: present
        update_cache: yes
        # name: Copy GitLab configuration file
        #copy:
        #src: "{{  }}"
        #dest: "{{ gitlab_config_file_path }}"
        #owner: root
        #group: root
        #mode: 0644
        #notify: Reconfigure and restart GitLab
