AWSTemplateFormatVersion: 2010-09-09
Description: "Docker tools"
Parameters:
  InstancesImageId:
    Type: String

  InstancesKeyName: 
    Type: String 

  InstanceTypeAnsible:
    Type: String

  InstanceTypeJenkins:
    Type: String

  InstanceTypeGitlab:
    Type: String

  InstanceTypeDatabase:
    Type: String

  InstanceTypeMonitoring:
    Type: String

Resources: 
  Ansible: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeAnsible
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "Ansible"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'privateToolsSecGroup'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetTools-mlm'
    
  Jenkins: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeJenkins
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "Jenkins"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'privateToolsSecGroup'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetTools-mlm'
 
  Gitlab: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeGitlab
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "Gitlab"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'PrivateSubnetTools-mlm'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetTools-mlm'

  Database: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeDatabase
        ImageId: !Ref InstancesImageId
        Tags: 
          -
            Key: "Name"
            Value: "Database"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'PrivateSubnetTools-mlm'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetTools-mlm'

  Monitoring: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeMonitoring
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "Monitoring"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'PrivateSubnetTools-mlm'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetTools-mlm'

Outputs:
  AnsibleID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Ansible
    Export:
      Name: !Sub 'AnsibleID-mlm'

  JenkinsID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Jenkins
    Export:
      Name: !Sub 'JenkinsID-mlm'

  GitlabID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Gitlab
    Export:
      Name: !Sub 'GitlabID-mlm'

  DatabaseID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Database
    Export:
      Name: !Sub 'DatabaseID-mlm'

  MonitoringID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Monitoring
    Export:
      Name: !Sub 'MonitoringID-mlm'