AWSTemplateFormatVersion: 2010-09-09
Description: "Docker tools"
Parameters:
  InstancesImageId:
    Type: String

  InstancesKeyName: 
    Type: String 

  InstanceTypeAnsible:
    Type: String

  InstanceTypeJenkins:
    Type: String

  InstanceTypeGitlab:
    Type: String

  InstanceTypeMonitoring:
    Type: String
    
  InstanceTypeBastion:
    Type: String
    
  BastionKeyName:
    Type: String
  
Resources: 
  Ansible: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeAnsible
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "Ansible"
          -
            Key: "project"
            Value: "docker-mlm"
          -
            Key: "role"
            Value: "Ansible"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'PrivateSecurityGroupIDTools-mlm'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetIDTools-mlm'
        UserData:
          Fn::Base64: !Sub |
            apt install python
    
  Jenkins: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeJenkins
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "Jenkins"
          -
            Key: "project"
            Value: "docker-mlm"
          -
            Key: "role"
            Value: "Jenkins"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'PrivateSecurityGroupIDTools-mlm'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetIDTools-mlm'
        UserData:
            Fn::Base64: !Sub |
              apt install python
 
  Gitlab: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeGitlab
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "Gitlab"
          -
            Key: "project"
            Value: "docker-mlm"
          -  
            Key: "role"
            Value: "Gitlab"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'PrivateSecurityGroupIDTools-mlm'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetIDTools-mlm'
        UserData:
            Fn::Base64: !Sub |
              apt install python

  ELK: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeMonitoring
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "ElK"
          -
            Key: "project"
            Value: "docker-mlm"
          -
            Key: "role"
            Value: "ELK"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'PrivateSecurityGroupIDTools-mlm'
        KeyName: !Ref InstancesKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PrivateSubnetIDTools-mlm'
        UserData:
            Fn::Base64: !Sub |
              apt install python

  Bastion: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType : !Ref InstanceTypeBastion
        ImageId: !Ref InstancesImageId
        Tags:
          -        
            Key: "Name"
            Value: "Bastion"
          - 
            Key: "project"
            Value: "docker-mlm"
          -  
            Key: "role"
            Value: "Bastion"
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': 'PublicSecurityGroupIDTools-mlm'
        KeyName: !Ref BastionKeyName
        SubnetId: !ImportValue
          'Fn::Sub': 'PublicSubnetIDTools-mlm'
        UserData:
            Fn::Base64: !Sub |
              apt install python
        
Outputs:
  AnsibleID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Ansible
    Export:
      Name: !Sub 'AnsibleID-mlm'

  JenkinsID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Jenkins
    Export:
      Name: !Sub 'JenkinsID-mlm'

  GitlabID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Gitlab
    Export:
      Name: !Sub 'GitlabID-mlm'

  ELKID:
    Description: The subnet ID to use for public web servers
    Value: !Ref ELK
    Export:
      Name: !Sub 'ELKID-mlm'

  BastionID:
    Description: The subnet ID to use for public web servers
    Value: !Ref Bastion
    Export:
      Name: !Sub 'BastionID-mlm'
