- name: Install Gitlab on Ubuntu
  hosts: gitlab
  gather_facts: false
  become: true
  tasks:
    - name: Set Postfix hostname
      debconf: name=postifx question="postfix/mailname" value="http://exemple.fr" vtype="string"

    - name: Set Postfix option type as internet site
      debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"

    - name: Download the install script
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /usr/bin/script.deb.sh
        mode: 0777

    - name: Execute the install script
      command: bash /usr/bin/script.deb.sh

    - name: Install Gitlab and its dependencies
      apt:
        name: "{{ packages }}"
        state: present
        force: yes
        update_cache: yes
      vars:
        packages:
          - curl
          - openssh-server
          - ca-certificates
          - postfix 
          - mailutils
          - gitlab-ce


