AWSTemplateFormatVersion: 2010-09-09

Description: Docker cluster root stack

Parameters:

  PublicSubnetProdCidr:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.0.0/27
      - 172.30.0.32/27
      - 172.30.0.64/27
      - 172.30.0.96/27
      - 172.30.0.128/27
      - 172.30.0.160/27
      - 172.30.0.192/27
      - 172.30.0.225/27
    Default: 172.30.0.0/27

  LoadBalancerSubnetProdCidr:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.0.0/27
      - 172.30.0.32/27
      - 172.30.0.64/27
      - 172.30.0.96/27
      - 172.30.0.128/27
      - 172.30.0.160/27
      - 172.30.0.192/27
      - 172.30.0.225/27
    Default: 172.30.0.32/27

  PrivateSubnetProdCidr:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.0.0/27
      - 172.30.0.32/27
      - 172.30.0.64/27
      - 172.30.0.96/27
      - 172.30.0.128/27
      - 172.30.0.160/27
      - 172.30.0.192/27
      - 172.30.0.225/27
    Default: 172.30.0.64/27

  PublicSubnetToolsCidr:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.1.0/27
      - 172.30.1.32/27
      - 172.30.1.64/27
      - 172.30.1.96/27
      - 172.30.1.128/27
      - 172.30.1.160/27
      - 172.30.1.192/27
      - 172.30.1.225/27
    Default: 172.30.1.0/27

  LoadBalancerSubnetToolsCidr:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.1.0/27
      - 172.30.1.32/27
      - 172.30.1.64/27
      - 172.30.1.96/27
      - 172.30.1.128/27
      - 172.30.1.160/27
      - 172.30.1.192/27
      - 172.30.1.225/27
    Default: 172.30.1.32/27

  PrivateSubnetToolsCidr:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.1.0/27
      - 172.30.1.32/27
      - 172.30.1.64/27
      - 172.30.1.96/27
      - 172.30.1.128/27
      - 172.30.1.160/27
      - 172.30.1.192/27
      - 172.30.1.225/27
    Default: 172.30.1.64/27

  InstancesImageId:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: ami-0a313d6098716f372

  InstancesKeyName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: devops_key
  
  BastionKeyName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: Bastion-mlm

  InstanceTypeManager:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.medium
      - t2.xlarge
      - c5n.xlarge
    Default: t2.medium
  
  InstanceTypeWorker:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.medium
      - t2.xlarge
      - c5n.xlarge
    Default: t2.medium

  InstanceTypeBastion:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.micro
      - t2.nano
    Default: t2.nano

  InstanceTypeAnsible:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.micro
      - t2.nano
    Default: t2.nano
  
  InstanceTypeJenkins:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.micro
      - t2.nano
    Default: t2.nano

  InstanceTypeGitlab:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.micro
      - t2.nano
    Default: t2.nano

  InstanceTypeMonitoring:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.micro
      - t2.nano
    Default: t2.nano

  UCPGPort:
    Type: Number
    Default: 443
  
  UCPGProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

  DTRGPort:
    Type: Number
    Default: 80
      
  DTRProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

  AppPort:
    Type: Number
    Default: 8080

  AppProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

Resources:

  NetworkStackProd:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/docker-mlm/Stacks/prod-network.yml"
      Parameters:
        PublicSubnetProdCidr: !Ref PublicSubnetProdCidr
        LoadBalancerSubnetProdCidr: !Ref LoadBalancerSubnetProdCidr
        PrivateSubnetProdCidr: !Ref PrivateSubnetProdCidr
      Tags:
        - Key: Name
          Value: NetworkStackProd-mlm

  InstancesStackProd:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/docker-mlm/Stacks/prod-instances.yml"
      Parameters:
        InstancesImageId: !Ref InstancesImageId
        InstancesKeyName: !Ref InstancesKeyName
        BastionKeyName: !Ref BastionKeyName
        InstanceTypeManager: !Ref InstanceTypeManager
        InstanceTypeWorker: !Ref InstanceTypeWorker
        InstanceTypeBastion: !Ref InstanceTypeBastion
      Tags:
        - Key: Name
          Value: InstancesStackProd-mlm
    DependsOn: NetworkStackProd 

  LoadBalancerStackProd:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/docker-mlm/Stacks/prod-lb.yml"
      Parameters:
        UCPGPort: !Ref UCPGPort
        UCPGProtocol: !Ref UCPGProtocol
        DTRGPort: !Ref DTRGPort
        DTRProtocol: !Ref DTRProtocol
        AppPort: !Ref AppPort
        AppProtocol: !Ref AppProtocol
      Tags:
        - Key: Name
          Value: LoadBalancerProd-mlm
    DependsOn: InstancesStackProd

  NetworkStackTools:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/docker-mlm/Stacks/tools-network.yml"
      Parameters:
        PublicSubnetToolsCidr: !Ref PublicSubnetToolsCidr
        LoadBalancerSubnetToolsCidr: !Ref LoadBalancerSubnetToolsCidr
        PrivateSubnetToolsCidr: !Ref PrivateSubnetToolsCidr
      Tags:
        - Key: Name
          Value: NetworkStackTools-mlm

  InstancesStackTools:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/docker-mlm/Stacks/tools-instances.yml"
      Parameters:
        InstancesImageId: !Ref InstancesImageId
        InstancesKeyName: !Ref InstancesKeyName
        BastionKeyName: !Ref BastionKeyName
        InstanceTypeBastion: !Ref InstanceTypeBastion
        InstanceTypeAnsible: !Ref InstanceTypeAnsible
        InstanceTypeJenkins: !Ref InstanceTypeJenkins
        InstanceTypeGitlab: !Ref InstanceTypeGitlab
        InstanceTypeMonitoring: !Ref InstanceTypeMonitoring
      Tags:
        - Key: Name
          Value: InstancesStackTools-mlm
    DependsOn: NetworkStackTools
