AWSTemplateFormatVersion: 2010-09-09
Description: Docker cluster root stack
Parameters:
  PublicSubnetCdir:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.0.0/27
      - 172.30.0.32/27
      - 172.30.0.64/27
      - 172.30.0.96/27
      - 172.30.0.128/27
      - 172.30.0.160/27
      - 172.30.0.192/27
      - 172.30.0.225/27
    Default: 172.30.0.0/27

  LoadBSubnetCdir:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.0.0/27
      - 172.30.0.32/27
      - 172.30.0.64/27
      - 172.30.0.96/27
      - 172.30.0.128/27
      - 172.30.0.160/27
      - 172.30.0.192/27
      - 172.30.0.225/27
    Default: 172.30.0.32/27

  PrivateSubnetCdir:
    Type: String
    MinLength: 8
    MaxLength: 19
    AllowedValues: 
      - 172.30.0.0/27
      - 172.30.0.32/27
      - 172.30.0.64/27
      - 172.30.0.96/27
      - 172.30.0.128/27
      - 172.30.0.160/27
      - 172.30.0.192/27
      - 172.30.0.225/27
    Default: 172.30.0.64/27

  InstancesImageId:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: ami-0a313d6098716f372

  InstancesKeyName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: devops_key
  
  BastionKeyName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: Bastion-mlm

  InstanceTypeManager:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.medium
      - t2.xlarge
      - c5n.xlarge
    Default: t2.medium
  
  InstanceTypeWorker:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.medium
      - t2.xlarge
      - c5n.xlarge
    Default: t2.medium

  InstanceTypeBastion:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.micro
      - t2.nano
    Default: t2.nano

  UCPGPort:
    Type: Number
    Default: 443
  
  UCPGProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

  DTRGPort:
    Type: Number
    Default: 80
      
  DTRProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

  AppPort:
    Type: Number
    Default: 8080

  AppProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

Resources:
  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm2/network_stacks.yml"
      Parameters:
        PublicSubnetCdir: !Ref PublicSubnetCdir
        LBSubnetCdir: !Ref LoadBSubnetCdir
        PrivateSubnetCdir: !Ref PrivateSubnetCdir
      Tags:
        - Key: Name
          Value: NetworkStack-mlm

  InstancesStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm2/instances_stacks.yml"
      Parameters:
        InstancesImageId: !Ref InstancesImageId
        InstancesKeyName: !Ref InstancesKeyName
        BastionKeyName: !Ref BastionKeyName
        InstanceTypeManager: !Ref InstanceTypeManager
        InstanceTypeWorker: !Ref InstanceTypeWorker
        InstanceTypeBastion: !Ref InstanceTypeBastion
      Tags:
        - Key: Name
          Value: InstancesStack-mlm

    DependsOn: NetworkStack 
  LoadBalancerStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm2/loadBalancer_stacks.yml"
      Parameters:
        UCPGPort: !Ref UCPGPort
        UCPGProtocol: !Ref UCPGProtocol
        DTRGPort: !Ref DTRGPort
        DTRProtocol: !Ref DTRProtocol
        AppPort: !Ref AppPort
        AppProtocol: !Ref AppProtocol
      Tags:
        - Key: Name
          Value: LoadBalancer-mlm
    DependsOn: InstancesStack 
