AWSTemplateFormatVersion: 2010-09-09
Description: "Docker cluster LoadBalancer"
Parameters:
  UCPGPort:
    Type: Number
  
  UCPGProtocol:
    Type: String

  DTRGPort:
    Type: Number
      
  DTRProtocol:
    Type: String

  AppPort:
    Type: Number

  AppProtocol:
    Type: String

Resources: 
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: "ipv4"
      Name: "LoadBalancer-mlm"
      Scheme: "internet-facing"
      SecurityGroups: 
          - !ImportValue 
            'Fn::Sub': 'LoadBalancerSecurityGroupIDProd-mlm'
      #SubnetMappings: [!Ref ---]
      Subnets: 
          - !ImportValue 
            'Fn::Sub': 'PublicSubnetIDProd-mlm'
          - !ImportValue 
            'Fn::Sub': 'LoadBalancerSubnetIDProd-mlm'
      Type: "application"
      Tags:
        -
          Key: "name"
          Value: "LoadBalancerProd-mlm"

  UCPGrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: yes
      HealthCheckIntervalSeconds: 300
      HealthCheckPort: !Ref UCPGPort
      HealthCheckProtocol: "HTTP"
      Name: "UCPGrp"
      Port: !Ref UCPGPort
      Protocol: !Ref UCPGProtocol
      VpcId: !ImportValue 
        'Fn::Sub': 'VPCProd-mlm'
      TargetType: instance 
      Targets: 
        -
          Id: !ImportValue 
            'Fn::Sub': 'Manager1ID-mlm'
          Port: !Ref UCPGPort
        -
          Id: !ImportValue 
            'Fn::Sub': 'Manager2ID-mlm'
          Port: !Ref UCPGPort
        -
          Id: !ImportValue 
            'Fn::Sub': 'Manager3ID-mlm'
          Port: !Ref UCPGPort
      Tags:
        -
          Key: "name"
          Value: "UCPGrp-mlm"

  DTRGrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: yes
      HealthCheckIntervalSeconds: 300
      HealthCheckPort: 443
      HealthCheckProtocol: "HTTP"
      Name: "DTRGrp"
      Port: !Ref DTRGPort
      Protocol: !Ref DTRProtocol
      VpcId: !ImportValue 
        'Fn::Sub': 'VPCProd-mlm'
      TargetType: instance 
      Targets: 
        -
          Id: !ImportValue 
            'Fn::Sub': 'WorkerDTRID-mlm'
          Port: !Ref DTRGPort
      Tags:
        -
          Key: "name"
          Value: "DTRGrp-mlm"

  AppGrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: yes
      HealthCheckIntervalSeconds: 300
      HealthCheckPort: !Ref AppPort
      HealthCheckProtocol: "HTTP"
      Name: "AppGrp"
      Port: !Ref AppPort
      Protocol: !Ref AppProtocol
      VpcId: !ImportValue 
        'Fn::Sub': 'VPCProd-mlm'
      TargetType: instance 
      Targets: 
        -
          Id: !ImportValue 
            'Fn::Sub': 'Manager1ID-mlm'
          Port: !Ref AppPort
        -
          Id: !ImportValue 
            'Fn::Sub': 'Manager2ID-mlm'
          Port: !Ref AppPort
        -
          Id: !ImportValue 
            'Fn::Sub': 'Manager3ID-mlm'
          Port: !Ref AppPort
        -
          Id: !ImportValue 
            'Fn::Sub': 'WorkerID-mlm'
          Port: !Ref AppPort
        -
          Id: !ImportValue 
            'Fn::Sub': 'WorkerDTRID-mlm'
          Port: !Ref AppPort

  ListenerUCP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
      - Type: "forward"
        TargetGroupArn: !Ref UCPGrp
      LoadBalancerArn: !Ref LoadBalancerProd
      Port: !Ref UCPGPort
      Protocol : !Ref UCPGProtocol

  ListenerDTR:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
      - Type: "forward"
        TargetGroupArn: !Ref DTRGrp
      LoadBalancerArn: !Ref LoadBalancerProd
      Port: !Ref DTRGPort
      Protocol : !Ref DTRProtocol

  ListenerAPP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
      - Type: "forward"
        TargetGroupArn: !Ref AppGrp
      LoadBalancerArn: !Ref LoadBalancerProd
      Port: !Ref AppPort
      Protocol : !Ref AppProtocol
