AWSTemplateFormatVersion: 2010-09-09

Description: "Network for Docker lab"

Parameters:  

  PublicSubnetProdCidr:
    Type: String

  LoadBalancerSubnetProdCidr:
    Type: String

  PrivateSubnetProdCidr: 
    Type: String

Resources: 

  VPCProd:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 172.30.0.0/24
      Tags:
        - Key: Name
          Value: VPCProd-mlm

  EIPProd:
    Type: 'AWS::EC2::EIP'
    DependsOn: PublicSubnetProd

  PublicSubnetProd:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCProd
      AvailabilityZone: us-east-1a
      CidrBlock: !Ref PublicSubnetProdCidr
      Tags:
        - Key: Name
          Value: PublicSubnetProd-mlm
    DependsOn: VPCProd

  LoadBalancerSubnetProd:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCProd
      AvailabilityZone: us-east-1b
      CidrBlock: !Ref LoadBalancerSubnetProdCidr
      Tags:
        - Key: Name
          Value: LoadBalancerSubnetProd-mlm
    DependsOn: VPCProd

  PrivateSubnetProd:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCProd
      CidrBlock: !Ref PrivateSubnetProdCidr
      Tags:
        - Key: Name
          Value: PrivateSubnetProd-mlm

  InternetGatewayProd:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: InternetGatewayProd-mlm
    DependsOn: VPCProd

  NatGatewayProd:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt 
        - EIPProd
        - AllocationId
      SubnetId: !Ref PublicSubnetProd
      Tags:
        - Key: Name
          Value: NatGatewayProd-mlm
    DependsOn: EIPProd

  VPCGatewayAttachmentProd:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGatewayProd
      VpcId: !Ref VPCProd

#  VPCGatewayAttachmentLB:
#    Type: 'AWS::EC2::VPCGatewayAttachment'
#    Properties:
#      InternetGatewayId: !Ref InternetGatewayLB
#      VpcId: !Ref VPC

  PublicRouteTableProd:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCProd
      Tags:
        - Key: Name
          Value: PublicRouteTableProd-mlm

  LoadBalancerRouteTableProd:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCProd
      Tags:
        - Key: Name
          Value: LoadBalancerRouteTableProd-mlm

  PrivateRouteTableProd:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCProd
      Tags:
        - Key: Name
          Value: PrivateRouteTableProd-mlm

  PublicRouteProd:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatewayProd
      RouteTableId: !Ref PublicRouteTableProd

  LoadBalancerRouteProd:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatewayProd
      RouteTableId: !Ref LoadBalancerRouteTableProd

  PrivateRouteProd:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayProd
      RouteTableId: !Ref PrivateRouteTableProd
      
  PeeringRouteProd:
  Type: AWS::EC2::Route
  Properties:
    DestinationCidrBlock: 172.30.1.0/24
    RouteTableId: !Ref PrivateRouteTableProd
    VpcPeeringConnectionId: !Ref VPCPeeringConnection

  PublicSubnetRouteTableAssociationProd:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTableProd
      SubnetId: !Ref PublicSubnetProd
    DependsOn: PublicRouteTableProd

  LoadBalancerSubnetRouteTableAssociationProd:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref LoadBalancerRouteTableProd
      SubnetId: !Ref LoadBalancerSubnetProd
    DependsOn: LoadBalancerRouteTableProd

  PrivateSubnetRouteTableAssociationProd:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PrivateRouteTableProd
      SubnetId: !Ref PrivateSubnetProd
    DependsOn: PrivateRouteTableProd

  PublicSecurityGroupProd:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: PublicSecurityGroupProd-mlm
      GroupDescription: public security group rules
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCProd
      Tags:
        - Key: Name
          Value: PublicSecurityGroupProd-mlm

  PrivateSecurityGroupProd:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: PrivateSecurityGroupProd-mlm
      GroupDescription: private security group rules
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 12376
          ToPort: 12388
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 10250
          ToPort: 10250
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 9099
          ToPort: 9099
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 7946
          ToPort: 7946
          CidrIp: 172.30.0.0/24
        - IpProtocol: udp
          FromPort: 7946
          ToPort: 7946
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 6443
          ToPort: 6444
          CidrIp: 172.30.0.0/24
        - IpProtocol: udp
          FromPort: 4789
          ToPort: 4789
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 2376
          ToPort: 2377
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 179
          ToPort: 179
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 172.30.0.0/24
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 172.30.0.0/24,172.30.1.0/24
      VpcId: !Ref VPCProd
      Tags:
        - Key: Name
          Value: PrivateSecurityGroupProd-mlm

  LoadBalancerSecurityGroupProd:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: LoadBalancerSecurityGroupProd-mlm
      GroupDescription: loadbalancer security group rules
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCProd
      Tags: 
        -
          Key: Name
          Value: LoadBalancerSecurityGroupProd-mlm  

  VPCPeeringConnection:  
  Type: AWS::EC2::VPCPeeringConnection
  Properties: 
    PeerVpcId: !Ref VPCProd
    Tags:
      - Key: Name
        Value: VpcPeeringConnection-mlm
    VpcId: !Ref VPCTools

Outputs:

  VPCIDProd:
    Description: VPCIDProd
    Value: !Ref VPCProd
    Export:
      Name: !Sub VPCIDProd-mlm

  PublicSubnetIDProd:
    Description: The subnet ID to use for public web servers
    Value: !Ref PublicSubnetProd
    Export:
      Name: !Sub PublicSubnetIDProd-mlm

  LoadBalancerSubnetIDProd:
    Description: The subnet ID to use for public web servers
    Value: !Ref LoadBalancerSubnetProd
    Export:
      Name: !Sub LoadBalancerSubnetIDProd-mlm

  PrivateSubnetIDProd:
    Description: The subnet ID to use for public web servers
    Value: !Ref PrivateSubnetProd
    Export:
      Name: !Sub PrivateSubnetIDProd-mlm

  PublicSecurityGroupIDProd:
    Description: The security group ID to use for public web servers
    Value: !GetAtt 
      - PublicSecurityGroupProd
      - GroupId
    Export:
      Name: !Sub PublicSecurityGroupIDProd-mlm
  
  LoadBalancerSecurityGroupIDProd:
    Description: The security group ID to use for public web servers
    Value: !GetAtt 
      - LoadBalancerSecurityGroupProd
      - GroupId
    Export:
      Name: !Sub LoadBalancerSecurityGroupIDProd-mlm

  PrivateSecurityGroupIDProd:
    Description: The security group ID to use for public web servers
    Value: !GetAtt 
      - PrivateSecurityGroupProd
      - GroupId
    Export:
      Name: !Sub PrivateSecurityGroupIDProd-mlm
