AWSTemplateFormatVersion: 2010-09-09
Description: Docker cluster root stack
Parameters:
  PublicSubnetCdir:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedValues: 
      - 172.30.0.0/24
      - 172.30.0.32/24
      - 172.30.0.64/24
      - 172.30.0.96/24
      - 172.30.0.128/24
      - 172.30.0.160/24
      - 172.30.0.192/24
      - 172.30.0.224/24
    Default: 172.30.0.0/24

  LBSubnetCdir:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedValues: 
      - 172.30.0.0/24
      - 172.30.0.32/24
      - 172.30.0.64/24
      - 172.30.0.96/24
      - 172.30.0.128/24
      - 172.30.0.160/24
      - 172.30.0.192/24
      - 172.30.0.224/24
    Default: 172.30.0.32/24

  PrivateSubnetCdir:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedValues: 
      - 172.30.0.0/24
      - 172.30.0.32/24
      - 172.30.0.64/24
      - 172.30.0.96/24
      - 172.30.0.128/24
      - 172.30.0.160/24
      - 172.30.0.192/24
      - 172.30.0.224/24
    Default: 172.30.0.64/24

  InstancesImageId:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: ami-0a313d6098716f372

  InstancesKeyName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: devops_key
  
  BastionKeyName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: Bastion-mlm

  InstanceTypeManager:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.medium
      - t2.xlarge
      - c5n.xlarge
    Default: t2.medium
  
  InstanceTypeWorker:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.medium
      - t2.xlarge
      - c5n.xlarge
    Default: t2.medium

  InstanceTypeBastion:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedValues: 
      - t2.micro
      - t2.nano
    Default: t2.nano

  UCPGPort:
    Type: Number
    Default: 443
  
  UCPGProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

  DTRGPort:
    Type: Number
    Default: 80
      
  DTRProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

  AppPort:
    Type: Number
    Default: 8080

  AppProtocol:
    Type: String
    AllowedValues: 
      - HTTP
      - HTTPS
    Default: HTTP

Resources:
  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm/network_stacks.yml"
      Parameters:
        PublicSubnetCdir: !Ref PublicSubnetCdir
        LBSubnetCdir: !Ref LBSubnetCdir
        PrivateSubnetCdir: !Ref PrivateSubnetCdir
      Tags:
        - Key: Name
          Value: '${NetworkStackName}'

  InstancesStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm/instances_stacks.yml"
      Parameters:
        InstancesImageId: !Ref InstancesImageId
        InstancesKeyName: !Ref InstancesKeyName
        BastionKeyName: !Ref BastionKeyName
        InstanceTypeManager: !Ref InstanceTypeManager
        InstanceTypeWorker: !Ref InstanceTypeWorker
        InstanceTypeBastion: !Ref InstanceTypeBastion
      Tags:
        - Key: Name
          Value: '${InstancesStackName}'

    DependsOn: NetworkStack 
  LoadBalancerStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm/loadBalancer_stacks.yml"
      Parameters:
        UCPGPort: !Ref UCPGPort
        UCPGProtocol: !Ref UCPGProtocol
        DTRGPort: !Ref DTRGPort
        DTRProtocol: !Ref DTRProtocol
        AppPort: !Ref AppPort
        AppProtocol: !Ref AppProtocol
      Tags:
        - Key: Name
          Value: LoadBalancer-mlm
    DependsOn: InstancesStack 
