---
# tasks file for docker
- name: "install docker requirements"
  apt:
   name: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
   state: present

- name: "get docker apt key"
  shell: "curl -fsSL {{docker_ee_url}}/ubuntu/gpg | sudo apt-key add -"

- name: "add docker source repo to apt"
  apt_repository: 
   repo: "deb [arch=amd64] {{docker_ee_url}} bionic stable-{{docker_ee_version}}"
   state: present

- name: "install docker"
  apt:
   update_cache: yes
   name: 
    - docker-ee
    - docker-ee-cli
    - containerd.io
   state: present


